# the random forest model by Sai Manmohan Mohanty - 2021A7PS1448P
# Group 09, Topic 29

# -*- coding: utf-8 -*-
"""Random Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_1hJINtzTVh0HyCoo3d6K2oOYRgVV9n
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

# configuration
data_dir = "./data"
city = "braga"

prod_file = os.path.join(data_dir, f"prod_{city}.csv")
rad_file  = os.path.join(data_dir, f"rad_{city}.csv")

# load data
prod = pd.read_csv(prod_file)
rad  = pd.read_csv(rad_file)

prod['Date'] = pd.to_datetime(prod['Date'])
rad['time']  = pd.to_datetime(rad['time'])

# merge on nearest time stamp
df = pd.merge_asof(
    prod.sort_values('Date'),
    rad.sort_values('time'),
    left_on='Date',
    right_on='time',
    direction='nearest'
)

df = df[df['shortwave_radiation(W/m2)'] > 0]

# train–test split by year
train_df = df[df['Date'].dt.year.isin([2019, 2020, 2021])]
test_df  = df[df['Date'].dt.year == 2022]

X_train = train_df[['shortwave_radiation(W/m2)', 'temperature(C)', 'cloud_cover(pc)']]
y_train = train_df['Produced Energy (kWh)']

X_test  = test_df[['shortwave_radiation(W/m2)', 'temperature(C)', 'cloud_cover(pc)']]
y_test  = test_df['Produced Energy (kWh)']

# random forest model
rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=12,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("=== Random Forest Results (Train 2019–2021, Test 2022) ===")
print("MAE :", mae)
print("RMSE:", rmse)
print("R^2 :", r2)

print("\nFeature Importances:")
for name, val in zip(X_train.columns, rf.feature_importances_):
    print(f"{name}: {val:.4f}")

# building results dataframe
results = test_df.loc[X_test.index, ['Date', 'Produced Energy (kWh)']].copy()
results['Date'] = pd.to_datetime(results['Date'])
results = results.sort_values('Date').reset_index(drop=True)

results['predicted'] = y_pred
results['residual'] = results['Produced Energy (kWh)'] - results['predicted']

# time series plot: actual vs predicted (hourly)
plt.figure(figsize=(14, 4))
plt.plot(results['Date'], results['Produced Energy (kWh)'], label='Actual', linewidth=1)
plt.plot(results['Date'], results['predicted'], label='Predicted', linewidth=1, alpha=0.8)
plt.xlabel('Date')
plt.ylabel('Produced Energy (kWh)')
plt.title('Random Forest — Actual vs Predicted (Hourly, Test: 2022)')
plt.legend()
plt.tight_layout()
plt.show()

# scatter: predicted vs actual
plt.figure(figsize=(6, 6))
plt.scatter(results['Produced Energy (kWh)'], results['predicted'], alpha=0.4, s=10)
maxv = max(results[['Produced Energy (kWh)', 'predicted']].max()) * 1.05
plt.plot([0, maxv], [0, maxv], color='red', linestyle='--', label='y = x')
plt.xlabel('Actual Produced Energy (kWh)')
plt.ylabel('Predicted Produced Energy (kWh)')
plt.title('Random Forest — Predicted vs Actual (Hourly)')
plt.legend()
plt.tight_layout()
plt.show()

# residuals histogram (just calcluates the difference between actual and predicted energy hourly)
plt.figure(figsize=(8, 4))
plt.hist(results['residual'], bins=50, alpha=0.8)
plt.axvline(results['residual'].mean(), color='red', linestyle='--',
            label=f"mean={results['residual'].mean():.3f}")
plt.xlabel('Residual (Actual - Predicted) [kWh]')
plt.title('Random Forest — Residuals Distribution (Hourly)')
plt.legend()
plt.tight_layout()
plt.show()

# daily aggregate comparison: checks the total output of a day against the predicted total output
daily = results.set_index('Date').resample('D').sum()[['Produced Energy (kWh)', 'predicted']]
daily.rename(columns={'Produced Energy (kWh)': 'actual_daily', 'predicted': 'pred_daily'}, inplace=True)

plt.figure(figsize=(14, 4))
plt.plot(daily.index, daily['actual_daily'], label='Actual daily sum', linewidth=1)
plt.plot(daily.index, daily['pred_daily'], label='Predicted daily sum', linewidth=1, alpha=0.8)
plt.xlabel('Date')
plt.ylabel('Daily Produced Energy (kWh)')
plt.title('Random Forest — Daily Sum: Actual vs Predicted (Test: 2022)')
plt.legend()
plt.tight_layout()
plt.show()

# recomputed mae
hourly_mae = mean_absolute_error(results['Produced Energy (kWh)'], results['predicted'])
daily_mae = mean_absolute_error(daily['actual_daily'], daily['pred_daily'])
print(f"Hourly MAE (recomputed): {hourly_mae:.4f} kWh")
print(f"Daily MAE             : {daily_mae:.4f} kWh/day")

print("\nExample predictions (first 8 rows):")
print(results.head(8).to_string(index=False))

# manual prediction - put weather conditions and the radiation and get an estimate of the output power
print("\nEnter values to get a prediction:")

rad_val = float(input("Shortwave radiation (W/m2): "))
temp_val = float(input("Temperature (C): "))
cloud_val = float(input("Cloud cover (%): "))

user_input = np.array([[rad_val, temp_val, cloud_val]])
predicted_energy = rf.predict(user_input)[0]

print(f"\nPredicted Produced Energy (kWh): {predicted_energy:.4f}")

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

# configuration
data_dir = "./data"
city = "faro"

prod_file = os.path.join(data_dir, f"prod_{city}.csv")
rad_file  = os.path.join(data_dir, f"rad_{city}.csv")

# load data
prod = pd.read_csv(prod_file)
rad  = pd.read_csv(rad_file)

prod['Date'] = pd.to_datetime(prod['Date'])
rad['time']  = pd.to_datetime(rad['time'])

# merge on nearest time stamp
df = pd.merge_asof(
    prod.sort_values('Date'),
    rad.sort_values('time'),
    left_on='Date',
    right_on='time',
    direction='nearest'
)

df = df[df['shortwave_radiation(W/m2)'] > 0]

# train–test split by year
train_df = df[df['Date'].dt.year.isin([2019, 2020, 2021])]
test_df  = df[df['Date'].dt.year == 2022]

X_train = train_df[['shortwave_radiation(W/m2)', 'temperature(C)', 'cloud_cover(pc)']]
y_train = train_df['Produced Energy (kWh)']

X_test  = test_df[['shortwave_radiation(W/m2)', 'temperature(C)', 'cloud_cover(pc)']]
y_test  = test_df['Produced Energy (kWh)']

# random forest model
rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=12,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("=== Random Forest Results (Train 2019–2021, Test 2022) ===")
print("MAE :", mae)
print("RMSE:", rmse)
print("R^2 :", r2)

print("\nFeature Importances:")
for name, val in zip(X_train.columns, rf.feature_importances_):
    print(f"{name}: {val:.4f}")

# building results dataframe
results = test_df.loc[X_test.index, ['Date', 'Produced Energy (kWh)']].copy()
results['Date'] = pd.to_datetime(results['Date'])
results = results.sort_values('Date').reset_index(drop=True)

results['predicted'] = y_pred
results['residual'] = results['Produced Energy (kWh)'] - results['predicted']

# time series plot: actual vs predicted (hourly)
plt.figure(figsize=(14, 4))
plt.plot(results['Date'], results['Produced Energy (kWh)'], label='Actual', linewidth=1)
plt.plot(results['Date'], results['predicted'], label='Predicted', linewidth=1, alpha=0.8)
plt.xlabel('Date')
plt.ylabel('Produced Energy (kWh)')
plt.title('Random Forest — Actual vs Predicted (Hourly, Test: 2022)')
plt.legend()
plt.tight_layout()
plt.show()

# scatter: predicted vs actual
plt.figure(figsize=(6, 6))
plt.scatter(results['Produced Energy (kWh)'], results['predicted'], alpha=0.4, s=10)
maxv = max(results[['Produced Energy (kWh)', 'predicted']].max()) * 1.05
plt.plot([0, maxv], [0, maxv], color='red', linestyle='--', label='y = x')
plt.xlabel('Actual Produced Energy (kWh)')
plt.ylabel('Predicted Produced Energy (kWh)')
plt.title('Random Forest — Predicted vs Actual (Hourly)')
plt.legend()
plt.tight_layout()
plt.show()

# residuals histogram (just calcluates the difference between actual and predicted energy hourly)
plt.figure(figsize=(8, 4))
plt.hist(results['residual'], bins=50, alpha=0.8)
plt.axvline(results['residual'].mean(), color='red', linestyle='--',
            label=f"mean={results['residual'].mean():.3f}")
plt.xlabel('Residual (Actual - Predicted) [kWh]')
plt.title('Random Forest — Residuals Distribution (Hourly)')
plt.legend()
plt.tight_layout()
plt.show()

# daily aggregate comparison: checks the total output of a day against the predicted total output
daily = results.set_index('Date').resample('D').sum()[['Produced Energy (kWh)', 'predicted']]
daily.rename(columns={'Produced Energy (kWh)': 'actual_daily', 'predicted': 'pred_daily'}, inplace=True)

plt.figure(figsize=(14, 4))
plt.plot(daily.index, daily['actual_daily'], label='Actual daily sum', linewidth=1)
plt.plot(daily.index, daily['pred_daily'], label='Predicted daily sum', linewidth=1, alpha=0.8)
plt.xlabel('Date')
plt.ylabel('Daily Produced Energy (kWh)')
plt.title('Random Forest — Daily Sum: Actual vs Predicted (Test: 2022)')
plt.legend()
plt.tight_layout()
plt.show()

# recomputed mae
hourly_mae = mean_absolute_error(results['Produced Energy (kWh)'], results['predicted'])
daily_mae = mean_absolute_error(daily['actual_daily'], daily['pred_daily'])
print(f"Hourly MAE (recomputed): {hourly_mae:.4f} kWh")
print(f"Daily MAE             : {daily_mae:.4f} kWh/day")

print("\nExample predictions (first 8 rows):")
print(results.head(8).to_string(index=False))

# manual prediction - put weather conditions and the radiation and get an estimate of the output power
print("\nEnter values to get a prediction:")

rad_val = float(input("Shortwave radiation (W/m2): "))
temp_val = float(input("Temperature (C): "))
cloud_val = float(input("Cloud cover (%): "))

user_input = np.array([[rad_val, temp_val, cloud_val]])
predicted_energy = rf.predict(user_input)[0]

print(f"\nPredicted Produced Energy (kWh): {predicted_energy:.4f}")



import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

# configuration
data_dir = "./data"
city = "lisbon"

prod_file = os.path.join(data_dir, f"prod_{city}.csv")
rad_file  = os.path.join(data_dir, f"rad_{city}.csv")

# load data
prod = pd.read_csv(prod_file)
rad  = pd.read_csv(rad_file)

prod['Date'] = pd.to_datetime(prod['Date'])
rad['time']  = pd.to_datetime(rad['time'])

# merge on nearest time stamp
df = pd.merge_asof(
    prod.sort_values('Date'),
    rad.sort_values('time'),
    left_on='Date',
    right_on='time',
    direction='nearest'
)

df = df[df['shortwave_radiation(W/m2)'] > 0]

# train–test split by year
train_df = df[df['Date'].dt.year.isin([2019, 2020, 2021])]
test_df  = df[df['Date'].dt.year == 2022]

X_train = train_df[['shortwave_radiation(W/m2)', 'temperature(C)', 'cloud_cover(pc)']]
y_train = train_df['Produced Energy (kWh)']

X_test  = test_df[['shortwave_radiation(W/m2)', 'temperature(C)', 'cloud_cover(pc)']]
y_test  = test_df['Produced Energy (kWh)']

# random forest model
rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=12,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("=== Random Forest Results (Train 2019–2021, Test 2022) ===")
print("MAE :", mae)
print("RMSE:", rmse)
print("R^2 :", r2)

print("\nFeature Importances:")
for name, val in zip(X_train.columns, rf.feature_importances_):
    print(f"{name}: {val:.4f}")

# building results dataframe
results = test_df.loc[X_test.index, ['Date', 'Produced Energy (kWh)']].copy()
results['Date'] = pd.to_datetime(results['Date'])
results = results.sort_values('Date').reset_index(drop=True)

results['predicted'] = y_pred
results['residual'] = results['Produced Energy (kWh)'] - results['predicted']

# time series plot: actual vs predicted (hourly)
plt.figure(figsize=(14, 4))
plt.plot(results['Date'], results['Produced Energy (kWh)'], label='Actual', linewidth=1)
plt.plot(results['Date'], results['predicted'], label='Predicted', linewidth=1, alpha=0.8)
plt.xlabel('Date')
plt.ylabel('Produced Energy (kWh)')
plt.title('Random Forest — Actual vs Predicted (Hourly, Test: 2022)')
plt.legend()
plt.tight_layout()
plt.show()

# scatter: predicted vs actual
plt.figure(figsize=(6, 6))
plt.scatter(results['Produced Energy (kWh)'], results['predicted'], alpha=0.4, s=10)
maxv = max(results[['Produced Energy (kWh)', 'predicted']].max()) * 1.05
plt.plot([0, maxv], [0, maxv], color='red', linestyle='--', label='y = x')
plt.xlabel('Actual Produced Energy (kWh)')
plt.ylabel('Predicted Produced Energy (kWh)')
plt.title('Random Forest — Predicted vs Actual (Hourly)')
plt.legend()
plt.tight_layout()
plt.show()

# residuals histogram (just calcluates the difference between actual and predicted energy hourly)
plt.figure(figsize=(8, 4))
plt.hist(results['residual'], bins=50, alpha=0.8)
plt.axvline(results['residual'].mean(), color='red', linestyle='--',
            label=f"mean={results['residual'].mean():.3f}")
plt.xlabel('Residual (Actual - Predicted) [kWh]')
plt.title('Random Forest — Residuals Distribution (Hourly)')
plt.legend()
plt.tight_layout()
plt.show()

# daily aggregate comparison: checks the total output of a day against the predicted total output
daily = results.set_index('Date').resample('D').sum()[['Produced Energy (kWh)', 'predicted']]
daily.rename(columns={'Produced Energy (kWh)': 'actual_daily', 'predicted': 'pred_daily'}, inplace=True)

plt.figure(figsize=(14, 4))
plt.plot(daily.index, daily['actual_daily'], label='Actual daily sum', linewidth=1)
plt.plot(daily.index, daily['pred_daily'], label='Predicted daily sum', linewidth=1, alpha=0.8)
plt.xlabel('Date')
plt.ylabel('Daily Produced Energy (kWh)')
plt.title('Random Forest — Daily Sum: Actual vs Predicted (Test: 2022)')
plt.legend()
plt.tight_layout()
plt.show()

# recomputed mae
hourly_mae = mean_absolute_error(results['Produced Energy (kWh)'], results['predicted'])
daily_mae = mean_absolute_error(daily['actual_daily'], daily['pred_daily'])
print(f"Hourly MAE (recomputed): {hourly_mae:.4f} kWh")
print(f"Daily MAE             : {daily_mae:.4f} kWh/day")

print("\nExample predictions (first 8 rows):")
print(results.head(8).to_string(index=False))

# manual prediction - put weather conditions and the radiation and get an estimate of the output power
print("\nEnter values to get a prediction:")

rad_val = float(input("Shortwave radiation (W/m2): "))
temp_val = float(input("Temperature (C): "))
cloud_val = float(input("Cloud cover (%): "))

user_input = np.array([[rad_val, temp_val, cloud_val]])
predicted_energy = rf.predict(user_input)[0]

print(f"\nPredicted Produced Energy (kWh): {predicted_energy:.4f}")



import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

# configuration
data_dir = "./data"
city = "setubal"

prod_file = os.path.join(data_dir, f"prod_{city}.csv")
rad_file  = os.path.join(data_dir, f"rad_{city}.csv")

# load data
prod = pd.read_csv(prod_file)
rad  = pd.read_csv(rad_file)

prod['Date'] = pd.to_datetime(prod['Date'])
rad['time']  = pd.to_datetime(rad['time'])

# merge on nearest time stamp
df = pd.merge_asof(
    prod.sort_values('Date'),
    rad.sort_values('time'),
    left_on='Date',
    right_on='time',
    direction='nearest'
)

df = df[df['shortwave_radiation(W/m2)'] > 0]

# train–test split by year
train_df = df[df['Date'].dt.year.isin([2019, 2020, 2021])]
test_df  = df[df['Date'].dt.year == 2022]

X_train = train_df[['shortwave_radiation(W/m2)', 'temperature(C)', 'cloud_cover(pc)']]
y_train = train_df['Produced Energy (kWh)']

X_test  = test_df[['shortwave_radiation(W/m2)', 'temperature(C)', 'cloud_cover(pc)']]
y_test  = test_df['Produced Energy (kWh)']

# random forest model
rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=12,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("=== Random Forest Results (Train 2019–2021, Test 2022) ===")
print("MAE :", mae)
print("RMSE:", rmse)
print("R^2 :", r2)

print("\nFeature Importances:")
for name, val in zip(X_train.columns, rf.feature_importances_):
    print(f"{name}: {val:.4f}")

# building results dataframe
results = test_df.loc[X_test.index, ['Date', 'Produced Energy (kWh)']].copy()
results['Date'] = pd.to_datetime(results['Date'])
results = results.sort_values('Date').reset_index(drop=True)

results['predicted'] = y_pred
results['residual'] = results['Produced Energy (kWh)'] - results['predicted']

# time series plot: actual vs predicted (hourly)
plt.figure(figsize=(14, 4))
plt.plot(results['Date'], results['Produced Energy (kWh)'], label='Actual', linewidth=1)
plt.plot(results['Date'], results['predicted'], label='Predicted', linewidth=1, alpha=0.8)
plt.xlabel('Date')
plt.ylabel('Produced Energy (kWh)')
plt.title('Random Forest — Actual vs Predicted (Hourly, Test: 2022)')
plt.legend()
plt.tight_layout()
plt.show()

# scatter: predicted vs actual
plt.figure(figsize=(6, 6))
plt.scatter(results['Produced Energy (kWh)'], results['predicted'], alpha=0.4, s=10)
maxv = max(results[['Produced Energy (kWh)', 'predicted']].max()) * 1.05
plt.plot([0, maxv], [0, maxv], color='red', linestyle='--', label='y = x')
plt.xlabel('Actual Produced Energy (kWh)')
plt.ylabel('Predicted Produced Energy (kWh)')
plt.title('Random Forest — Predicted vs Actual (Hourly)')
plt.legend()
plt.tight_layout()
plt.show()

# residuals histogram (just calcluates the difference between actual and predicted energy hourly)
plt.figure(figsize=(8, 4))
plt.hist(results['residual'], bins=50, alpha=0.8)
plt.axvline(results['residual'].mean(), color='red', linestyle='--',
            label=f"mean={results['residual'].mean():.3f}")
plt.xlabel('Residual (Actual - Predicted) [kWh]')
plt.title('Random Forest — Residuals Distribution (Hourly)')
plt.legend()
plt.tight_layout()
plt.show()

# daily aggregate comparison: checks the total output of a day against the predicted total output
daily = results.set_index('Date').resample('D').sum()[['Produced Energy (kWh)', 'predicted']]
daily.rename(columns={'Produced Energy (kWh)': 'actual_daily', 'predicted': 'pred_daily'}, inplace=True)

plt.figure(figsize=(14, 4))
plt.plot(daily.index, daily['actual_daily'], label='Actual daily sum', linewidth=1)
plt.plot(daily.index, daily['pred_daily'], label='Predicted daily sum', linewidth=1, alpha=0.8)
plt.xlabel('Date')
plt.ylabel('Daily Produced Energy (kWh)')
plt.title('Random Forest — Daily Sum: Actual vs Predicted (Test: 2022)')
plt.legend()
plt.tight_layout()
plt.show()

# recomputed mae
hourly_mae = mean_absolute_error(results['Produced Energy (kWh)'], results['predicted'])
daily_mae = mean_absolute_error(daily['actual_daily'], daily['pred_daily'])
print(f"Hourly MAE (recomputed): {hourly_mae:.4f} kWh")
print(f"Daily MAE             : {daily_mae:.4f} kWh/day")

print("\nExample predictions (first 8 rows):")
print(results.head(8).to_string(index=False))

# manual prediction - put weather conditions and the radiation and get an estimate of the output power
print("\nEnter values to get a prediction:")

rad_val = float(input("Shortwave radiation (W/m2): "))
temp_val = float(input("Temperature (C): "))
cloud_val = float(input("Cloud cover (%): "))

user_input = np.array([[rad_val, temp_val, cloud_val]])
predicted_energy = rf.predict(user_input)[0]

print(f"\nPredicted Produced Energy (kWh): {predicted_energy:.4f}")